# SPDX-License-Identifier: AGPL-3.0-or-later
# PR CI workflow - validates and tests on pull requests to master
# Does NOT build or push Docker images

name: PR CI

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Validate and Test
    uses: ./.github/workflows/validate-and-test.yml
    with:
      verbose: false
